### ISSUE TITLE
Problem in converting from c\side to al in standard objects

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#1153]
Hi team, 
I've added new factbox in 22 page (in C\Side).
![image](https://user-images.githubusercontent.com/29101017/33846319-6501d594-deb7-11e7-94c8-36d45b0a9510.png)

And I want to export this in AL.
I do all the steps from here https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-txt2al-tool  
And in the end I get this .al file
![image](https://user-images.githubusercontent.com/29101017/33846368-9015571a-deb7-11e7-8fd8-ee5dff00548e.png)

So everything is ok, except Control1900000007. This is standard control, but AL don't "see" it.

I also noticed that I can do 
![image](https://user-images.githubusercontent.com/29101017/33846406-c9396dd8-deb7-11e7-94d8-3b614d1d2acc.png)

But can not do 
![image](https://user-images.githubusercontent.com/29101017/33846421-d5828c6e-deb7-11e7-91fd-71673bbf6f88.png)

As I see the main difference between this two standard controls is <> in C\SIDE
![image](https://user-images.githubusercontent.com/29101017/33846455-f877a4c0-deb7-11e7-9699-f4af094eb6f2.png)

So is this a bug?
Or there any workaround?

Thanks

**Comment by markbrummel** [comment]
It's super annoying and hugely time consuming. I had to fix a few dozen pages today.

Thanks Dmitri

**Comment by kalberes** [comment]
I assume that you have run exporttonewsyntax on the exported page 22 before running txt2al. Isn't it?
How is in your exported page22.al that control named?

**Comment by markbrummel** [comment]
This is converting a delta file to a page extension. Not a full page object.

**Comment by DominikDitoIvosevic** [comment]
Hi @dkatson @markbrummel . So the first issue you have described is the one which has been fixed recently. The issue was that the extension model between delta files and page extension differs in it's core. delta files only specified text changes meaning since .txt files had a flattened list of controls you would add the part after the area (int delta files the operation was called InsertAfter).
In page extension you are NOT adding the part after the area. You are adding it INSIDE of it. That's described by the "AddFirst" operation which means you are adding an element as a first child of the parent.

This has been identified by  Jonathan @jcooper01 in https://github.com/Microsoft/AL/issues/875 and has been fixed.

In newer versions of the platform+al extension you will need to specify the flag -ExportToNewSyntax when creating the delta files (you will need to recreate them). This add some more information about the control tree to the delta file so that we can create correct page extensions.

Example:
Compare-NAVApplicationObject -OriginalPath "C:\PageWith2Controls.txt" -ModifiedPath "C:\PageWith3Controls.txt" -ExportToNewSyntax

As for the second issue. I'm not really sure what you are describing. Could you please open another issue with a clear repro?

Best,
Dominik

**Comment by DanielGoehler** [comment]
Hi @DominikDitoIvosevic,

with the **February Update** I still have this Problem. I exported the Object with the New Syntax. The Rest is in the attached Zip-File [Problem.zip](https://github.com/Microsoft/AL/files/1733623/Problem.zip). I used `Compare-NAVApplicationObject -OriginalPath .\ORG\*.txt -ModifiedPath .\MOD\*.txt -DeltaPath .\DELTA -ExportToNewSyntax ` to create the Delta-File and used **txt2al** to Convert to AL. The Pre-Compiler in VScode still says `'Control1900000007' is not found in the target`.

```
pageextension 70000001 pageextension70000001 extends "Warehouse Activity Lines" 
{
    // version NAVW111.00.00.19846

    layout
    {
        addfirst(Control1900000007)
        {
            part(Control5273128;"Bin Content Factbox")
            {
                SubPageLink = "Item No."=FIELD("Item No."),
                              "Location Code"=FIELD("Location Code"),
                              "Variant Code"=FIELD("Variant Code"),
                              "Unit of Measure Code"=FIELD("Unit of Measure Code");
                Visible = false;
            }
        }
    }
}
```

**Comment by GreatScott000** [comment]
This problem still appears in the March update too.

@markbrummel how did you "fix" these?

**Comment by DominikDitoIvosevic** [comment]
The problem is that we are using control names for container type controls but in AL we reference them by type (content, factboxes). The fix would be to fix the names to be of control's area type.

That or wait for my fix which I'm working on

**Comment by SimOlivier** [comment]
I am still having this issue with NAV CU5. Where was the change made? In the txt2al tool?

**Comment by DanielGoehler** [comment]
@SimOlivier Did had a change to test this, but it supposed to be fixed in the May Update (https://blogs.msdn.microsoft.com/nav/2018/05/25/developer-preview-may-2018-update/)

**Comment by DanielGoehler** [comment]
When announcing the March Update (https://blogs.msdn.microsoft.com/nav/2018/03/23/developer-preview-march-update/), they said: „Please note, that the improvements announced in this blog post are not available in Dynamics NAV 2018 and the following cumulative updates of Dynamics NAV 2018.“

**Comment by OlivierHellmann** [comment]
@DanielGoehler thank you for your answer i am going to download the developer preview now

to your other answer: do you want to say that the developer preview will also not be available in later cumulative updates? Is this Statement also relevant for the may update?
