### ISSUE TITLE
Testfield keyword gives ambiguous error

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1268]
`TESTFIELD(Status, Status::Open);` has
```
[AL] The call is ambiguous between the following methods or properties: 'TestField(Joker, Integer)' and 'TestField(Joker, Integer)'
procedure TestField(Field : Joker, Value : Guid)
Tests whether the contents of a field match a given value.
```

`TESTFIELD("Allow Line Disc.", false);` has
```
[AL] The call is ambiguous between the following methods or properties: 'TestField(Joker, Boolean)' and 'TestField(Joker, Boolean)'
procedure TestField(Field : Joker, Value : Guid)
Tests whether the contents of a field match a given value.
```

**Comment by SirBETE** [comment]
Is this solved in the february update? ( #1507)

**Comment by StanislawStempin** [comment]
This bug is not fixed yet. To give you some background on our labelling process:
- label 'bug'  means that we acknowledged the issue as a bug and added to our bug backlog
- labels 'bug' and 'accepted' means that we started working on the bug
- labels 'bug' 'ships-in-future-update' and assigned milestone  means that we have fixed the bug in our codebase and it will be available in the marked Milestone release or in the next private Docker image shared through NDA-bound Collaborate program
- label 'delivered' and issue Closed - means that the fix has been shipped in a public preview release

**Comment by StanislawStempin** [comment]
I've also updated the FAQ to provide more information about labels and issue lifecycle:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#what-do-all-the-labels-assigned-to-issues-mean

**Comment by SirBETE** [comment]
Ok Thank you for the information :)

**Comment by thpeder** [comment]
Yes, it does seem to have been solved as part of the other bug.
Thanks for reporting it!
