### ISSUE TITLE
Page doesn't close

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1641]
I've written a code on Action of page 1 to Run page 2 , fetch certain value from page 2 then on OnQueryClose page of page 2 a call is made back to page 1.
Here, call is made and value is fetched but the page 2 doesn't close whereas it runs in an  never ending loop

**Comment by StanislawStempin** [comment]
It sounds very similar to #1640, we will look into both issues.

**Comment by thpeder** [comment]
@Chris-Dsilva It sounds like a problem that was fixed in the lastest update (February 2018).

**Comment by Chris-Dsilva** [comment]
@thpeder  I'm using NAV CU 2 update i.e the Feb update of NAV 2018 still the issue persist

**Comment by StanislawStempin** [comment]
February Update refers to the latest Developer Preview release for Dynamics 365 "Tenerife". Please see this FAQ entry for more details on NAV 2018 issues: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#nav-2018-issues

**Comment by thpeder** [comment]
@Chris-Dsilva The bug was that it would by default return false instead of true as it is done in C/SIDE. So if you explicitly exit with true then it should work.
