### ISSUE TITLE
Editable property only works on pages and not tables

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1667]
I am working on NAV 2018 CU 2. I had set the Editable as false in the table but that didn't work. It still allows to edit in the RTC but if Editable = false is set in the page it works fine.

**Comment by lvanvugt** [comment]
Same experience here.

**Comment by StanislawStempin** [comment]
Thanks for reporting.

**Comment by StanislawStempin** [comment]
This bug has been fixed in February Dev Preview. The support team ported the fix back to NAV 2018 CU4 as well

**Comment by TKapitan** [comment]
I have tested it on NAV 2018 CU04, it still happens. I set up editable = false on my new table, but the field is still editable on the page...

**Comment by StanislawStempin** [comment]
My bad, this hotfix will be part of CU5 and not CU4.
