### ISSUE TITLE
"Table XXXX is missing a matching permission set"

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#1880]
I have permission set XML file in the workspace including the table, but still I have this error. How the permission set is tested? Which rules must be followed?

Having the file with this in workspace and still table 50100 have no matching permission set>
![image](https://user-images.githubusercontent.com/110221/38072988-501b2c4a-3329-11e8-8bb1-47b30655c7c0.png)

**Comment by ajkauffmann** [comment]
It seems that this issue is now blocking tenant customizations with tables included for publishing on Business Central.

**Comment by kalberes** [comment]
This has been fixed locally but has not made he build for BC. It will be available for the first update though.
Until then it should be suppressed with a custom ruleset rule.

**Comment by RobAnderson42** [comment]
To clarify, we did take this fix for Business Central, so it shouldn't be blocking tenant customizations. The fix will be available in Visual Studio Code in the next update.

**Comment by paulcart-tnp** [comment]
I'm still seeing this issue when trying to deploy an extension to Business Central trial tenants using the "Upload an Extension" function. At the moment this means we can't deploy any tenant specific extensions that contain new tables. I'm aware that the bug still exists in VSCode, but we're still seeing it in BC.

**Comment by hemisphera** [comment]
I hate to hijack this issue for my question but ...
How the heck did you get this XML structure out of Business Central? I have spent an entire day now trying to figure this out and get my permission sets included in my app. I took me long enough to actually **produce** the output from XMLport 9171 and 9172 (they are not linked anywhere in Business Central) right now. Now that I have those files I face the same issue as #2005. Are those XMLports even meant to still be used or I am supposed to write the XML "manually"?

**Comment by waldo1001** [comment]
I hate doing this with PowerShell:
- create permissionset/permission
- find your way to the docker container
- export with Powershell
- get your file to your app

I just created a xml-snippet as part of my extension:
https://marketplace.visualstudio.com/items?itemName=waldo.crs-al-language-extension

**Comment by paulcart** [comment]
@DominikDitoIvosevic  yep, and when it published to BC the permission set is created (as a Tenant Permission Set) with all the correct permissions. My user account has SUPER, but even if I apply the apps specific permission set I still get no permission to the tables.

It feels like it might be a licence issue as opposed to permissions?

**Comment by DominikDitoIvosevic** [comment]
@paulcart I'm not that familiar with how permissions work. Could you please provide us with repro steps?

**Comment by waldo1001** [comment]
@paulcart , if you are super, you have all rights possible. So if you are still not able to access whatever you put in the permission-xml, then it's most probably a license issue indeed.  Permission do not override licenses.

**Comment by sbuescher** [comment]
I had the same issue. Since today it seems to be fixed, right?

**Comment by StanislawStempin** [comment]
If you are still having this issue, could you please open a support ticket? 
We believe that code-wise the relevant bugs have been fixed but some tenants might not have the fix applied yet and support will assist in finding the exact state of your tenant.

**Comment by paulcart** [comment]
Hi, it's working perfectly today, so it must've just been my tenant was waiting for the fix. Thanks for your help!

**Comment by shortcreeker** [comment]
I have developed an extension that adds a new table using the "Microsoft Sandbox" and I am getting this "Table XXXX is missing a matching permission set" error when I try to deploy the App to a live client. (it deploys fine to the SandBox)
I do not have a permission.xml file. Where do I find this file if I am using the Sandbox and cannot run a Power-Shell command?

**Comment by waldo1001** [comment]
I added snippets for that in the CRS AL Language Extension.  Just install that vscode extension,  create an xml file and use the snippet...

**Comment by shortcreeker** [comment]
Waldo,

Thanks for creating this extension! I have in installed. I have created an extension that include a Table 50100 JobPlanSetStatus

What would the vales in the xml file need to be for RoleID, RoleName, ObjectType and ObjectId?

Thanks
Ezra

**Comment by shortcreeker** [comment]
How do I retrieve a list of RoleID's and RoleNames's from the Sandbox?

**Comment by shortcreeker** [comment]
When I turn on the al.enableCodeAnalysis then I get this error, with this set to false the App still will not upload to a live D365BC Client, what am I missing?  
![permissions](https://user-images.githubusercontent.com/39204269/40150396-a1af68b8-5936-11e8-84d2-e78970c18bb3.jpg)
![table](https://user-images.githubusercontent.com/39204269/40150400-a897177a-5936-11e8-8ff8-975c80d07b55.jpg)
![error](https://user-images.githubusercontent.com/39204269/40150466-f848b0e4-5936-11e8-9add-868317b961df.jpg)

**Comment by waldo1001** [comment]
It's not a valid xml for permissionsets.  check this:
`
<PermissionSets>
  <PermissionSet RoleID="SomeRoleId" RoleName="Some Role Name">
    <Permission>
      <ObjectType>TableData</ObjectType>
      <ObjectID>50100</ObjectID>
      <ReadPermission>Yes</ReadPermission>
      <InsertPermission>Yes</InsertPermission>
      <ModifyPermission>Yes</ModifyPermission>
      <DeletePermission>Yes</DeletePermission>
      <ExecutePermission>No</ExecutePermission>
      <SecurityFilter />
    </Permission>
  </PermissionSet>
</PermissionSets>
`

**Comment by shortcreeker** [comment]
I entered exactly like you recommended, then saved all files. I am still getting the same error....
![screen1](https://user-images.githubusercontent.com/39204269/40188321-e73a4a62-59b6-11e8-91b8-e709fd19bcb8.jpg)

**Comment by waldo1001** [comment]
@TheDenSter  is right.

It actually should all work.  but I realized I had to restart my VSCode to have the code analyzer realize it is a correct file.  It did just compile and work though.  

I tried:
```
<PermissionSets>
    <PermissionSet RoleID="SomeRoleId" RoleName="Some Role Name">
        <Permission>
            <ObjectType>TableData</ObjectType>
            <ObjectID>50100</ObjectID> 
            <ReadPermission>Yes</ReadPermission>
            <InsertPermission>Yes</InsertPermission>
            <ModifyPermission>Yes</ModifyPermission>
            <DeletePermission>Yes</DeletePermission>
            <ExecutePermission>0</ExecutePermission>
            <SecurityFilter />
        </Permission>
    </PermissionSet>
</PermissionSets>
```
and
```
<PermissionSets>
    <PermissionSet RoleID="SomeRoleId" RoleName="Some Role Name">
        <Permission>
            <ObjectType>0</ObjectType>
            <ObjectID>50100</ObjectID> <!-- SomeTable -->
            <ReadPermission>1</ReadPermission>
            <InsertPermission>1</InsertPermission>
            <ModifyPermission>1</ModifyPermission>
            <DeletePermission>1</DeletePermission>
            <ExecutePermission>0</ExecutePermission>
            <SecurityFilter />
        </Permission>
    </PermissionSet>
</PermissionSets>
```
I was able to publish both of them to business central.

I used my snippet "tpermissionsetcollection"
![image](https://user-images.githubusercontent.com/12088142/40241564-a1a3946c-5abb-11e8-9d4c-deffdcb04727.png)

**Comment by TheDenSter** [comment]
Great snippet, you're just full of handy ideas :)

**Comment by DominikDitoIvosevic** [comment]
We have just the snippet for you :) available in our Developer preview

![image](https://user-images.githubusercontent.com/6378638/40471215-40292740-5f36-11e8-8d37-0d2dfd954d08.png)

**Comment by shortcreeker** [comment]
I still get the error in VS Code, however the file properly imports to a live client.

On May 28, 2018, at 7:24 AM, Andreas Pröhl <notifications@github.com<mailto:notifications@github.com>> wrote:


@waldo<https://github.com/waldo>: I have the same issue like @shortcreeker<https://github.com/shortcreeker>. The bug is closed but i see no solution. VsCode always says "Table 'XXXXX' is missing a matching permission set.
I have a valid PermissionSet.xml (created with the snippets from you) and the version of the vscode extension is "0.15.18771".

I used number range 79400..79499.

**Comment by waldo1001** [comment]
@shortcreeker , I found that 0.15.18771 is not the one where it is fixed.  I have the problem there as well - although this is the current version online.

I also have an insider version (0.16.14305) and it's fixed there:

![image](https://user-images.githubusercontent.com/12088142/40618744-c23188f4-6292-11e8-9b59-6b804dd75072.png)

**Comment by JosepPages** [comment]
I get the same error.
When will the version (0.16.14305) be in Marketplace?
Thanks.

**Comment by waldo1001** [comment]
@JosepPages , just that you know - for the time being, you could "bend the rule" by overruling with your own coderule.

I described it here:
http://www.waldo.be/2018/03/26/enable-the-updated-code-analysis-for-al/

It is no solution, I know, but as far as I know, it will create your permissionset with deployment, and this is merely a problem with the codecop.

**Comment by JSebastianN** [comment]
I use the **PerTenantExtensionCop** analysis Ruleset and get the error:
id": "PTE0004", "Table '6181276' is missing a matching permission set."

I have created a Permission.xml file - but it does not relieve me of the errors.
I am using AL Language version 0.15.18771

Should I just be using a newer (Development) build of AL Language?

**Comment by waldo1001** [comment]
did you restart VScode? - something that's necessary ...

**Comment by waldo1001** [comment]
@JSebastianN , as I said above, I found that 0.15.18771 is not the one where it is fixed. I have the problem there as well - although this is the current version online.  
Can you test with a later build?

**Comment by JSebastianN** [comment]
I have just downloaded 2018 CU6 with AL Language 0.12.17091

Also I should now have access to the Daily BC Docker Build, so perhaps this includes a better Error message when uploading the Extension to BC.

I will keep you updated
