### ISSUE TITLE
FlowField error, converted code

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#2273]
Bear with me, not sure if this is a bug. Again, exported the table using NAV2018 RTM from our production system with ExportToNewSyntax and then used the Txt2AL.exe from the top-secret daily build docker system.

Again, this is an old table that just sits in our system. Nobody touched it for like 20 years except for upgrading from version to version.

The three flowfields look the same to me but only one gives an error.

![image](https://user-images.githubusercontent.com/7205122/40140482-5a2c18e8-5953-11e8-8ae0-9b29afebfe20.png)

**Comment by StanislawStempin** [comment]
I would recommend trying on the latest version of C/SIDE to do ExportToNewSyntax. There were a few bugs fixed in the export code since NAV 2018 RTM.

Only the first calc formula in your screenshot is correct. The other two are missing double quotes around identifiers with the dot and the space and I suspect the syntax error in the second formula causes parsing to go wrong for the rest of the fields and doesn't report the other errors.

**Comment by markbrummel** [comment]
Yes, the quotes are the problem and my guess was also that they are already going wrong in the initial finsql export.

I will install the whole docker thing at the customers site and see if we can fit the bits together. I'd like to get most of the errors out by the time you guys ship this fall and move our mods to extensions.

**Comment by qutreson** [comment]
Hi @markbrummel, could you still reproduce the issue after using the latest version of C/SIDE?

**Comment by markbrummel** [comment]
Have not checked yet. Hope to have time this week.
