### ISSUE TITLE
[NavigatePage] group.label visible property always evaluates boolean expression as true

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#4242]
**Describe the bug**
Hi,
I want to make a label visible only if two fields have the same value (password verification). 
When I put a boolean expression in the Visible property, the label is always evaluated to true, even if I put 
`Visible = (2=3);`
if I force **false** value, the label is not displayed.

**To Reproduce**

The label is in a group in an area of a page of **PageType = NavigatePage**.

Make the Visible property of the label equals to a boolean expression
-> the label visibility behavior is always as if the visible property is **true**

**Screenshots**
AL

![image](https://user-images.githubusercontent.com/29598240/48847976-2a4de400-eda3-11e8-9ffd-b1314ff9e076.png)

BC

![image](https://user-images.githubusercontent.com/29598240/48848047-536e7480-eda3-11e8-8d2b-043e053080f9.png)

Additionnal informations:
If I add the StyleExpr property to the label and set the same expression as the Visible Property:
The label is Visible, but the Style doesn't.

**Versions:**
 - AL Language: 2.0.48254
 - Business Central: 13.0 (24630)

**Comment by AndreyKorepanov** [comment]
Hi @JulienDecottignies, thank you for reporting the issue. I could not reproduce the issue with the latest build. It might have been already fixed, then it will be available in the next version. The other option is that some other page parameters or setting might affect the label behavior. Could you, please, provide the small sample of the page/project demonstrating the problem.

**Comment by JulienDecottignies** [comment]
Hi @AndreyKorepanov ,

I've just tried with the latest version (W1 13.0 (25789)) and still have the samed behaviour.
See the sample bellow:

```
page 8052586 "DKS Assisted Setup Wizard"
{
    PageType = NavigatePage;
    Caption = 'Setup Wizard';
    layout
    {
        area(Content)
        {
            group(SecondPage)
            {
                Caption = '';
                Visible = (_CurrentStep = 2);
                group("Set up your <account> Credentials")
                {
                    Caption = 'Set up your <account> credentials';
                    group("Setup Instruction")
                    {
                        Caption = '';
                        InstructionalText = 'Provide your <account> User Name and Password in the dedicated fields. When complete, hit the "Store Credentials" button.';
                    }
                    group(CredentialsPart)
                    {
                        Caption = 'Credentials';
                        field(UserName; _UserName)
                        {
                            Caption = '<account> User Name';
                            ToolTip = 'Your <account>Login';
                            Editable = true;
                            NotBlank = true;
                        }
                        field(PassWord; _UserPassword)
                        {
                            Caption = '<account>User Password';
                            ToolTip = 'Your <account> Password';
                            Editable = true;
                            NotBlank = true;
                            ExtendedDatatype = Masked;
                        }
                        field(PwdCheck; _PwdCheck)
                        {
                            Caption = 'Password Verification';
                            ToolTip = 'The same you provided above';
                            Editable = true;
                            NotBlank = true;
                            ExtendedDatatype = Masked;

                            trigger OnValidate()
                            var
                            begin
                                if _PwdCheck <> _UserPassword then begin
                                    _PwdsOk := false;
                                    Clear(_UserPassword);
                                    Clear(_PwdCheck);
                                end
                                else
                                    _PwdsOk := true;
                            end;
                        }

                        label(PwdCheckErr)
                        {
                            Caption = 'Passwords are not matching. Please provide the same password.';
                            Style = Unfavorable;
                            Visible = not _PwdsOk;

                        }
                }
            }
```

**Comment by AndreyKorepanov** [comment]
@JulienDecottignies thank you, we'll try it out.

**Comment by JulienDecottignies** [comment]
@AndreyKorepanov ,
That's exactly how I temporarily fixed this problem :) 
Thank you for the answers.

**Comment by ekawatani** [comment]
Hi @jdhuntington , this is by design that fields do not react to Visible property changes after OnOpenPage. A workaround is to wrap it inside a group like Andrey suggested. I agree it's a bit weird, but there are historical reasons behind this, and it's not a straightforward fix we can do. I'll close this bug. Please see https://docs.microsoft.com/en-us/dynamics-nav/visible-property
