### ISSUE TITLE
Unhandled Exception: System.FormatException: The AL server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by rdebath** [Microsoft/AL#4628]
**Describe the bug**
The AL server is crashing; it appears to be the `AppSourceCop` and related to field numbers outside the required number range.

This looks a little similar to #4588 and may be a duplicate, however, even so it's a different manifestation.
Note: al-2.1.79379 -- ALLanguage-V13cu3 does not crash and gives the out of range errors.

```
Microsoft (R) AL Compiler version 2.1.1.30356
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'Default Project' containing '1' files at '12:40:24.586'.


Compilation ended at '12:40:27.874'.

Success: The package is created.

Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.Contract.ProtocolDiagnostic..ctor(Diagnostic diagnostic) in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\LanguageServerContract\ProtocolDiagnostic.cs:line 34
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.CreateProtocolDiagnostic(Diagnostic d, Int32& combinedHashCode) in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 374
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.AddDiagnosticsFromSyntaxTreeToBuilder(ImmutableArray`1 diagnostics, Int32& combinedHashCode, ArrayBuilder`1 builder, SyntaxTree syntaxTree) in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 337
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<CreateDiagnosticResponse>d__7.MoveNext() in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<>c__DisplayClass1_1.<<GetDiagnostics>b__0>d.MoveNext() in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 12:42:57] Connection to server got closed. Server will restart.
[Error - 12:42:57] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)

Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.Contract.ProtocolDiagnostic..ctor(Diagnostic diagnostic) in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\LanguageServerContract\ProtocolDiagnostic.cs:line 34
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.CreateProtocolDiagnostic(Diagnostic d, Int32& combinedHashCode) in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 374
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.AddDiagnosticsFromSyntaxTreeToBuilder(ImmutableArray`1 diagnostics, Int32& combinedHashCode, ArrayBuilder`1 builder, SyntaxTree syntaxTree) in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 337
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<CreateDiagnosticResponse>d__7.MoveNext() in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<>c__DisplayClass1_1.<<GetDiagnostics>b__0>d.MoveNext() in C:\a\45\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Error - 12:43:03] Connection to server got closed. Server will not be restarted.
[Error - 12:43:03] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\Robert\.vscode\extensions\microsoft.al-2.1.95890\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)

```

**To Reproduce**
Clone https://github.com/rdebath/ALHelloWorld/tree/issue4588 Note branch **issue4588**
Open the `HelloWorld.al` file.

**Expected behavior**
No crashing please. A display of the actual issues with the code would be nice too 😁  

**Versions:**
Name: AL Language
Id: microsoft.al
Description: AL development tools for Dynamics 365 Business Central
Version: 2.1.95890
Publisher: Microsoft

**Comment by qutreson** [comment]
@rdebath we pushed a new update of the AL extension on the marketplace (version 3.0.121490), can you try using it and tell us if it fixes your issue?

**Comment by rdebath** [comment]
Version 3.0.121490 from marketplace is working correctly in the repository I provided above.
However, it looks like the current from the bcsandbox-master is an earlier version that's still broken.

**Comment by qutreson** [comment]
This seems to be as expected. For now the fix is only available in the AL extension published in the VS Code marketplace, but it should be available soon in our daily deployments and as part of the next CU for the April 19 release. Closing the issue as is now fixed.
