### ISSUE TITLE
Opening a dialog supress other gui interactions in web client

### ISSUE THREAD

**Issue by larswestman** [microsoft/AL#4979]
If you have opened a dialog and try to do a Message() or Hyperlink() before you close the dialog then only the dialog will show. This applies to the web client. In RTC it works fine.

This code only shows "Hello world":
```
var
        MyDialog: Dialog;
    begin
        MyDialog.Open('Hello world');
        message('App published: Hello world');
        Sleep(1000);
        MyDialog.Close();
    end;
```

This code shows "Hello world" and "App published: Hello world":
```
var
        MyDialog: Dialog;
    begin
        MyDialog.Open('Hello world');
        Sleep(1000);
        MyDialog.Close();
        message('App published: Hello world');
    end;
```

Runtime 3.0
AL: 3.0.126610

**Comment by JohanStenberg100** [comment]
Hi @larswestman!

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
* Open a support request to CSS through the PartnerSource portal
* Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by larswestman** [comment]
So if I download latest insider build it works there?

It's not super clear where to report things. Is this repo only for issues with the AL compiler found in bcinsider.azurecr.io/bcsandbox-master?

**Comment by JohanStenberg100** [comment]
Hi again @larswestman,

1) No, but since this is a web client issue, we don't accept the bug. Instead you should use the support channels.

2) I have updated the README - I understand that it's confusing and we'll try to do better. We only accept bugs / suggestions etcetera for the AL compiler and the Development Tools in this repository.

Thanks!

**Comment by larswestman** [comment]
Still not super clear on what belongs here or not.

Use this filter and have a look: is:issue is:open web client 

It's a real mess trying to report findings as the situation is right now...

**Comment by JohanStenberg100** [comment]
Hi @larswestman, this repository **only** accepts issues or suggestions regarding the AL compiler and the Development Tools. We will clean up our issue backlog when we have capacity. Do you have a general BC bug, please file it using support channels. 

We also have some other GitHub repositories where you can file other issues, if they fit the repo's guidelines.
