### ISSUE TITLE
After vscode update: Can't debug/publish anymore with older versions of the AL vscode extension

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#6368]
**Describe the bug**
I am not sure if this is a case for the customer support, but we are developing for 140CU6 with vscode and are using the v3.0.168874 VSIX Version (Microsoft recommends to use the vsix for the target BC version). The last vscode update made it impossible to debug with this version, because the following error appears: "Couldn't find a debug adapter descriptor for debug type 'al' (extension might have failed to activate)"

Debugging works with the newest AL vsix.

Edit:
The debugging with the newest vscode is broken between the al vsix versions 4.0.249486 and 5.0.254558.

**To Reproduce**
Steps and to reproduce the behavior:
1. Open project
2. Press F5 or (Command Palette: AL Publish)
3. Error (see screenshot) pops up

**Expected behavior**
I should be able to debug even with the newest vscode version.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/7450586/101979786-f11d9080-3c57-11eb-851e-47cfa6a82e74.png)

**5. Versions:**

 - AL Language: v3.0.168874

 - Business Central: 14.7.37609.0

**Comment by ishwarsharma016** [comment]
I am running into the same error.

AL Language: v4.0.206840
Business Central: 15.2 (Platform 15.0.38951.0 + Application 15.2.39040.0)

**Comment by epernst** [comment]
Any updates? We are having the problem with BC 14.16.
Until then we are staying on v. 1.5.1 which can be downloaded here:
[https://code.visualstudio.com/updates/v1_51](url)

**Comment by atoader** [comment]
Hi! "Microsoft recommends to use the vsix for the target BC version)." That's actually not correct. We recommend that you use the latest VSIX from the marketplace when working against BC 13.0 or later. There is a readme on the latest DVD releases that states that you should use the VSIX from the marketplace.

**Comment by dannoe** [comment]
We are developing for runtime 3.2. With the old vsix we can use features like ShowCaption, CaptionClass, MultiLine, Editable, these are not supported by newest VSIX from the marketplace. The newest VSIX only supports 3.0 or 4.0.
4.0 is too new to be used with BC14 and 3.0 doesn't support the previously mentioned features. 
@atoader What should we do?

**Comment by pborring** [comment]
We versioned the compiler from the beginning (via the app.json version property). While we ship VSIX on the DVD/artifact, we recommend using the latest AL VSIX on the VS Code Marketplace to get new features and bug fixes, and we only test/bug fix on the latest VSIX.

Now it looks like ShowCaption, CaptionClass, MultiLine, Editable were introduced in 4.0, but backported to 3.2 NST/compiler. Latter should have meant that these should have been changed to be marked as available from 3.2 in all VSIX'es newer than the build for v3.2, but that is not the case - it is only in more recent builds of v3 VSIX'es.

Thus we will use this GitHub entry to track fixing that (marking those features as supported from 3.2 and forward, allowing you to use the newest VS Code Marketplace AL VSIX, and setting target version to 3.2 (for NST support).

Until then, it seems your only option is to use the older VSIX together with the previous VS Code version.

Thanks for raising this

**Comment by achim-t** [comment]
The current extension version doesn't support a runtime <1. 

![image](https://user-images.githubusercontent.com/11352910/102492077-68e12600-4071-11eb-9b6c-a7c87f872e76.png)

We had to use a (much) older version. Will we be stuck with VSC 1.15.1?

**Comment by AbsolutelyFreeWeb** [comment]
Helllo, I'm getting this error when compiling with vsix 2.169331 (BC13CU2) on vscode 1.52.
Will this be fixed as well ? runtime is 2.1

**Comment by cherabomb** [comment]
We are having this issue developing in AL Language for Dynamics NAV 2018 using VSCode, as mentioned in the linked, duplicate ticket. We are forced to use the "AL Language" VSIX version released for our NAV version (0.13.149996) and cannot use versions from the marketplace. We have uninstalled the latest Visual Studio Code version and reinstalled version 1.51 to be able to continue working.

**Comment by kalberes** [comment]
This issue has been fixed and will most likely be available in teh vsix packagefound on the DVD for the Cumulative Update 38 for Microsoft Dynamics NAV 2018

**Comment by dannoe** [comment]
@kalberes @atoader Is the mentioned backport of the 3.2 runtime to the newest vsix (marketplace) still happening?

**Comment by qutreson** [comment]
@dannoe we also fixed the runtime incompatibility issue and we just pushed a new version of the AL extension to the VS Code marketplace. The fix is in version 6.1.397164.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 20837 and VS Code Extension Version 7.0.397166. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by Inrego** [comment]
Will runtime 0.12 be supported?

**Comment by atoader** [comment]
The 0.12 runtime will not be supported by the AL extension from the marketplace. For NAV 2018, you should use the VSIX from the DVD. For Business Central 12.0 and higher, you should use the VSIX from the marketplace.

**Comment by Inrego** [comment]
Problem is that vsix doesn't work with vscode 1.52 and up..
So all I'm looking for, is being able to develop with an update vscode..

**Comment by atoader** [comment]
As Kalman stated, a fix will be available in the next CU of NAV 2018 which will make the VSIX from the DVD compatible with the latest release of Visual Studio Code. Until then, you should use an older version of VSCode with the extension from the DVD.

**Comment by Inrego** [comment]
He said that an update is coming which will support runtime 0.13.x

So when developing for runtime 0.12, we can never update vscode, since it won't be supported. Is that correct?

**Comment by KSH-audibene** [comment]
Is fix avalable in CU38 for NAV2018? I cannot see that in the description of the update?

**Comment by cherabomb** [comment]
Yes, installing the CU fixes it. We are now running NAV 2018 CU39 and I can confirm the problem is resolved.
