### ISSUE TITLE
AA0244 should not warn about event publisher arguments with same name as global variable

### ISSUE THREAD

**Issue by dzzzb** [Microsoft/AL#7081]
We are getting this:
![image](https://user-images.githubusercontent.com/63455896/174041199-a5f842f4-5474-4a3a-b47e-2dbf6fd5f1de.png)

[Another user](https://github.com/microsoft/AL/issues/6488#issuecomment-1157439328) is getting it:
![image](https://user-images.githubusercontent.com/63455896/174041257-38e3d918-9507-40fd-8f54-1391e92c4dce.png)

This IMO is not helpful to diagnose, as since there cannot be a body of the publisher, we can't possibly get confused and use the wrong local vs global...! So I think event publisher procedures should be exempted from this new rule.

Note that I can't reproduce this quickly, so it seems inconsistent in when/whether it warns about such cases:
![image](https://user-images.githubusercontent.com/63455896/174041504-9ff35046-acfc-47c1-a687-2388d4db804c.png)

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.2.639332
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by jwikman** [comment]
I agree! 
Now we've got some work to do with adding pragmas.... 😕

**Comment by fvet** [comment]
Can we have the same fix for the AA024**5** rule as well?
 
![image](https://user-images.githubusercontent.com/25268332/175001919-da08b7a2-5c3b-4bec-9b8c-df1dc231b2e1.png)

![image](https://user-images.githubusercontent.com/25268332/175001963-e6a2ac64-ff87-4e85-8035-cf71f20725af.png)

![image](https://user-images.githubusercontent.com/25268332/175002015-fa755ae2-89fb-46ab-a29d-ceb6287db437.png)

**Comment by nndobrev** [comment]
Hello everyone, new vsix will be released to marketplace later today/tomorrow fixing both AA0244 and AA0245. Thank you for reporting the issue.

**Comment by dnpb** [comment]
Thank you!

**Comment by nndobrev** [comment]
@dnpb, this should be fixed in the latest vsix available on market place version 9.3.642746.

**Comment by MatthewMcCarthy7** [comment]
I have version 9.3.642746 installed and I'm still getting the warning.

![image](https://user-images.githubusercontent.com/32099690/175350451-2e7f7afb-d10d-41c2-afdf-2a93cddade66.png)

**Comment by NKarolak** [comment]
@nndobrev Same for me: it's definitely not fixed in v9.3.642746 :-(
![image](https://user-images.githubusercontent.com/34504100/175482956-31152f0f-62c0-4308-a23c-e6bc7eb92421.png)

**Comment by nndobrev** [comment]
Hi, unfortunately, you are right and new version will come soon. Meanwhile, we decided to enhance the reach of AA0244: It will cover  IntegrationEvents, that have GlobalVarAccess set to true, in any other cases Events and EventSubscribers won't be covered by AA0244 or AA0245.

**Comment by dnpb** [comment]
I would almost risk saying that Subscribers _should_ be warned - they cannot change the argument names of course, but they can change their global variables names to not be the same and invite confusion... or ideally they would not use global variables at all ;-)

Just my 2p though

**Comment by NKarolak** [comment]
My pipelines are saying: the warning AA0244 is gone for containers build upon BC  20.2.41144.42860, but it still or again exists for next minor BC 20.3.42815.0

**Comment by nndobrev** [comment]
We are reverting the change (AA0244 and AA0245) for an oncoming vsix to the marketplace (coming very soon), but the rule will be present, and work as intended (+ @dnpb comment) in the insider builds. We just want to get more feedback from our AL developers before releasing it publicly to marketplace and official builds.

**Comment by dnpb** [comment]
Thanks :-)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 43437 and VS Code Extension Version 10.0.650082. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
