### ISSUE TITLE
txt2al.exe: OptionCaptionML in Table Extension

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#731]
I would be great if the conversion of **OptionCaptionML** in _Table Extension_ in txt2al.exe would optimized. Currently the result is the following:
```
modify("Type")
    {
      OptionCaptionML = DEU="""Standard Text"",Sachkonto,Artikel,Ressource,,""Artikel Zu-/Abschlag"",,,Debitor,Kreditor,Katalogartikel,""Zuständigkeitseinheiten""";
ENU="""Standard Text"",""G/L Account"",Item,Resource,,""Item Charge"",,,Customer,Vendor,""Nonstock Item"",""Responsibility Center""";
    }
```
The Pre-Complier in VS Code says:
> [AL] Syntax error, string literal expected (9,29) 
> [AL] Length of the identifier cannot exceed 120 characters (9,29)

A good result e. g. would be:
```
modify("Type")
    {
      OptionCaptionML=DEU='Standard Text,Sachkonto,Artikel,Ressource,,Artikel Zu-/Abschlag,,,Debitor,Kreditor,Katalogartikel,Zuständigkeitseinheiten',
                      ENU='Standard Text,G/L Account,Item,Resource,,Item Charge,,,Customer,Vendor,Nonstock Item,Responsibility Center';
    }
```

**Comment by StanislawStempin** [comment]
This should have been fixed together with #553

**Comment by DominikDitoIvosevic** [comment]
We are moving away from ML syntax in the future and you will be able to specify this in an industry accepted xliff file which you can use to translate things with many translation services/applications

**Comment by DanielGoehler** [comment]
With November Update: Issue still exists. I also added "features": "TranslationFile" to app.json. How will the CaptionML moved to that’s new xliff File?

**Comment by DominikDitoIvosevic** [comment]
@DanielGoehler please read the https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-work-with-translation-files to understand how we are transitioning to the xliff file approach. features:TranslationFile will provide you with compiler warnings where you need to update your source code.
Could you clarify what is the issue with indentation?

**Comment by DanielGoehler** [comment]
@DominikDitoIvosevic Sorry for my confusion. For Table Extension everything works fine now. For the indentation I create a new issue: #981
