### ISSUE TITLE
Microsoft.Data.SqlClient - Class Properties Not visible

### ISSUE THREAD

**Issue by AmeyDeshTQ** [microsoft/AL#7372]
Hi there,

We reference Microsoft.Data.SqlClient DLL to connect to SQL server from our app; however, our code is not compiling against BC22 

the properties on the SqlCommand, SqlConnection classes are no longer accessible, we can only access the methods

We also observed this behaviour happening on V4.0.0.0 of Microsoft.Data.SqlClient Dll which ships with BC22, if we download the latest version 5.1.1 from Nuget  then we can access the properties and the app compiles but we still can't publish it as Business Central is not able to figure out the latest DLL which we copied in the Add-ins folder 

here are some screenshots from a sample app

1. When referencing the default version shipped with BC22

![image](https://user-images.githubusercontent.com/126790075/231727908-17ff7c19-d974-4f7d-b25a-10f4c09609f8.png)

2. Referencing the latest version of Microsoft.Data.SqlClient (copied to Add-ins folder)
 The app compiles but publishing fails 
![image](https://user-images.githubusercontent.com/126790075/231728609-1798b81b-fde1-458f-b6f7-cb63bd980afb.png)

PS: I'm not using any containers, the application is installed locally on my machine 

Can you please advise

**Comment by AmeyDeshTQ** [comment]
Can you please provide an update on this?

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

The reason why this is out of scope is because this is to do with the version of SqlClient that is shipped in BC22 by the runtime, so this needs to be evaluated by the runtime team. I do know that there was a big shift in the runtime to move to .net core, and that probably impacted this scenario. However, that team needs to be the one to look into this and advise what is supported now.

**Comment by ap3rus** [comment]
@AmeyDeshTQ could you please share your configuration for the assembly probing paths you have in the extension that hits this issue? If not already, can you try adding the path `Microsoft.Data.SqlClient\4.0.2\lib\netstandard2.1` to the list (where `Microsoft.Data.SqlClient\4.0.2` is a path to extracted NuGet package Microsoft.Data.SqlClient version 4.0.2)?

We do support this package, we in fact have some AL tests in our continuous integration that ensure it works, therefore I suspect there might be some conflicts during assembly resolution (for example wrong target framework or ambiguous shared dependencies).

**Comment by AmeyDeshTQ** [comment]
Here you go - 

![image](https://github.com/microsoft/AL/assets/126790075/a6119ecd-f4ba-4ec4-bf74-875811eefb55)


Also, many other users have faced this issue.

**Comment by ap3rus** [comment]
As the BC 22 has changed runtime to .NET 6, when you upgrade an app that was designed for BC21 or earlier, and if the app is using .NET interop types, you need to ensure that the probing paths are updated accordingly, they may not include paths that contain legacy .NET Framework assemblies, except in cases where you explicitly want to use .NET Framework compatibility mode - in which case you may still not reference legacy GAC as it will conflict with .NET 6 runtime assemblies.

**Comment by ap3rus** [comment]
@AmeyDeshTQ thanks for the details, could you please try changing the order so that BC Service path comes after .NET 6 and Microsoft.Data.SqlClient folders?

    "al.assemblyProbingPaths": [
      ".\\.netpackages",
      "C:\\Program Files\\dotnet\\shared\\Microsoft.AspNetCore.App\\6.0.15",
      "C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\6.0.15",
      "C:\\Program Files\\dotnet\\shared\\Microsoft.WindowsDesktop.App\\6.0.15",
      "Microsoft.Data.SqlClient\\4.0.2\\lib\\netstandard2.1",
      "C:\\Program Files\\Microsoft Dynamics 365 Business Central\\220\\Service"
    ]

**Comment by ap3rus** [comment]
@AmeyDeshTQ @tgb-sw

We have identified an issue in the server that prevents it from publishing extensions that depends on certain metadata from Microsoft.Data.SqlClient, we are working on a fix. It only affects the server part of the publishing after compilation is successful in vscode.

**Comment by KristofKlein** [comment]
any news on thisone ? i think it is the same issue I face with mine 
https://github.com/microsoft/AL/issues/7406

**Comment by AmeyDeshTQ** [comment]
@KristofKlein - We have officially raised this with Microsoft and they are working on this issue

will let you know once the issue is resolved

**Comment by ap3rus** [comment]
@AmeyDeshTQ  @KristofKlein the issue should be fixed in platform versions from 22.0.57812.0, it's included in on-prem build 22.3 and above, and in all online versions.

**Comment by mjvisintin** [comment]
I see this issue is closed but we just upgraded to BC22 using 22.5 and I am still having this issue.
I am able to compile the application using microsoft.Data.dll but the server is not finding the SqlClient functionality when the server compiles it during publishing.

Is anyone else still experiencing this?

Thanks,

Michael

**Comment by szaragozanb** [comment]
October, 2024 and I'm facing this issue.

I don't understand because it seems to be solver in version BC22 and I'm in BC24.

My target is onPrem, My Dll is 5.0.0.0, etc

What happens to me is that as @AmeyDeshTQ @KristofKlein @tgb-sw descrive in all their comments. 

I have configurated the .netpackages folder, and al.assemblyprobingpaths and I'm not able to see all the properties that SqlCommand would must have.

![image](https://github.com/user-attachments/assets/3381b236-0aea-4ad1-a3cf-2bd68f5432ae)

Where is CommandText? CommandTimeOut? etc

Please .. if anyone can provide any entire example it would be very helpfull .. I haven't found any doc , post, etc to implement Microsoft.Data.Client using AL

**Comment by tgb-sw** [comment]
Hi szaragozanb,

the missing properties and methods are defined in System.Data.Common.

In vscode System.Data.Common is not found or the wrong version.

I simply put System.Data.Common.dll in my case Version 6.0.1623.17311 in the .netpackages folder. After that the missing properties show up:
![Image](https://github.com/user-attachments/assets/0f4aa688-ca88-4319-885b-5faed0ad4bae)

If I remove it from the .netpackages folder of my al project and restart vscode it exactly looks like in your screenshot.

I have this working with BC23. In case .net version of Microsoft.Data.SqlClient in BC24 has changed it maybe necessary to use a newer version of System.Data.Common.dll. But for sure you have missing depency of Microsoft.Data.SqlClient in vscode.

Hope this helps

Thomas

**Comment by szaragozanb** [comment]
> Hi szaragozanb,
> 
> the missing properties and methods are defined in System.Data.Common.
> 
> In vscode System.Data.Common is not found or the wrong version.
> 
> I simply put System.Data.Common.dll in my case Version 6.0.1623.17311 in the .netpackages folder. After that the missing properties show up: ![Image](https://github.com/user-attachments/assets/0f4aa688-ca88-4319-885b-5faed0ad4bae)
> 
> If I remove it from the .netpackages folder of my al project and restart vscode it exactly looks like in your screenshot.
> 
> I have this working with BC23. In case .net version of Microsoft.Data.SqlClient in BC24 has changed it maybe necessary to use a newer version of System.Data.Common.dll. But for sure you have missing depency of Microsoft.Data.SqlClient in vscode.
> 
> Hope this helps
> 
> Thomas


Yes! this help me!

Thanks Thomas!!!!!!!!!!!!!!
