### ISSUE TITLE
Tooltips on tableextension are not translated

### ISSUE THREAD

**Issue by sybrenwille** [microsoft/AL#7778]
**1. Describe the bug**
Tooltips on tableextension are not translated

**2. To Reproduce**
- Add a new field to a table extension and create a tooltip for this field.
- Produce the XLIFF file and translate the tooltip into a different language.
- Upon opening the client, the field's tooltip remains in English.

Note: if you do the same with a tooltip on page level it still works as expected

**3. Expected behavior**
The tooltip should be in the translation specified in the XLIFF File.

**4. Actual behavior**
The tooltip remains always in English

**5. Versions:**

- AL Language: 13.0.1027618
- Visual Studio Code: 1.87.2
- Business Central: 24.02

Internal work item: [AB#548298](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548298)

**Comment by guidorobben** [comment]
We have the same issue! Any news on this? Now we still have to add the tooltip on the page.

**Comment by guidorobben** [comment]
Factboxes have the same issue

**Comment by guidorobben** [comment]
Any news on this? This shouldnt be that hard to fix?

**Comment by thloke** [comment]
Sorry for the lack of update on this. Is the tableextension and table in the same app? If so, this is an issue that we've just got a fix for.

We'll be backporting the fix to BC24 and BC25 to address this issue. Since it's a server-side fix, it won't be dependent on a new version of the compiler. I'll close this issue once the hotfix of BC24 is rolled out.

If the table and tableextension are **not** in the same app, then this is likely a different issue. Let us know if this is the case, since it would need to be looked into.

**Comment by sybrenwille** [comment]
The table and table extension are **not** in the same table.

Create a Table extension on the Purchase Line for instance and put the Tooltip on the table field.
When you now use this new field on a page extension of the Purchase Order it always remains English and doesn't use the translated xliff value

**Comment by guidorobben** [comment]
Indeed, the table and table extension are **not** in the same App.

**Comment by guidorobben** [comment]
So we are getting close to 25. Will this be fixed in 25.0?

**Comment by sybrenwille** [comment]
> So we are getting close to 25. Will this be fixed in 25.0?

Tested this in BC25.0 still not working in there.

When can we expect a fix for this? 
Since the introduction of this functionality in BC24 it's not working.

**Comment by guidorobben** [comment]
Ok, so this will nog be fixed in 25.0. Will this be on the roadmap for 25.1?

**Comment by salgiza** [comment]
@thloke Could you please give us any feedback on this?  It's a bit frustrating that, 6 months later, we can't fully migrate our apps to use tooltips on tables because of this bug.

**Comment by thloke** [comment]
All I can say is that the bug is in our backlog of bugs, it's just a long backlog at the moment. :(

I'll bump its priority at least so this gets picked up before the other github bugs. Sorry for how long it's taken to get to this bug.

**Comment by guidorobben** [comment]
Any more news on this?

**Comment by KoenLagerwaard** [comment]
When will this issue be fixed? Everytime I create a pageextension I now have to make sure that I also add the ToolTip there as otherwise it wont be translated.

**Comment by guidorobben** [comment]
Can you Bump it again?!

**Comment by guidorobben** [comment]
![Alt Text](https://tenor.com/view/gjirlfriend-gif-14457952604098199169)

**Comment by sybrenwille** [comment]
Not tested it yet, but it seems there is something fixed in 25.3 according to the Changelog:


> 560754 | Tooltips on the table extension are not translated.

**Comment by guidorobben** [comment]
We tested all the extension objects and it indeed seems to work.

**Comment by MODUSCarstenScholling** [comment]
@guidorobben @sybrenwille  That is completely strange. I have just tested the following German releases (all OnPrem):

- 25.0, 25.3: With client language en-US: missing when in table extension works in page extension, client language de-DE: tooltip works for both
- 24.5: Both client languages, en-US and de-DE work for table extension and page extension tooltip

For us it is the English original tooltip, which is missing, the German translation is shown correctly (page AND table extensions).

App compiled with version: 15.0.1290655

**Comment by KoenLagerwaard** [comment]
Found another issue: 

When adding a field from another extension to a page, the tooltip will not be available. I have to copy the tooltip from the table extension field to the page.

**Comment by SVinchi** [comment]
The original issues related to translation of tooltips has been fixed in major version 24, 25 and onwards. 

Another issue mentioned here about adding tooltip from another extension has also been fixed in major 25 and onwards.

Therefore, I'm closing this issue,
